### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by elad-bar** [TOomaAh/emby_exporter_go#14]
Everytime I start the docker container it gets to that error,
Configurations is according to the manual, read also about similiar issue that fixed August a year ago, made sure all configurations are aligned.

## Docker Compose
```yaml
version: "3"
services:
  emby-exporter:
    image: bagul/goemby_exporter:latest
    container_name: emby-exporter
    hostname: emby-exporter
    restart: unless-stopped
    ports:
      - 9210:9210
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /path/emby-exporter:/config
    env_file:
      - ../env/emby-exporter.env
```

### ../env/emby-exporter.env
```env
CONFIG_FILE=/config/config.yml
```

## Configuration file:
```yaml
server:
  url: http://IP
  port: 8096
  token: "CREATED IN API KEYS"
  userID: "USER ID FROM URL AFTER GET INTO PROFILE profile.html?userId="
```

## Logs
```log
2023/09/16 19:21:14 Beginning to serve on port 9210
2023/09/16 19:21:14 You can see the metrics on http://localhost:9210/metrics
panic: runtime error: integer divide by zero
goroutine 22 [running]:
TOomaAh/emby_exporter_go/emby.(*Server).GetSessions(0xc00023c080)
	/app/emby/server.go:109 +0x665
TOomaAh/emby_exporter_go/emby.(*EmbyClient).GetMetrics(0xc000124050)
	/app/emby/client.go:56 +0x15d
TOomaAh/emby_exporter_go/metrics.(*EmbyCollector).Collect(0xc00014e080, 0xc00015ef60?)
	/app/metrics/emby_collector.go:43 +0x45
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:446 +0x10d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:457 +0x4bd
```
