### ISSUE TITLE
Premature exporter exit

### ISSUE THREAD

**Issue by oregonpillow** [TOomaAh/emby_exporter_go#46]
https://github.com/TOomaAh/emby_exporter_go/blob/e941e2ec7ffdcff9f3995915c69770925ee6b18b/internal/app/app.go#L41

The container exits as soon as it cannot connect to emby. There is no retry loop, or backoff logic which would make it more robust. I have a problem that when my containers shut down for backups, because the emby server is started after the exporter, then the exporter basically never runs because it's already excited after the first attempt.

One solutions is that users could add a healthcheck to their emby server and force the exporter to check the health status before starting. For example:
```yml
services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    healthcheck:
        test: ["CMD-SHELL", "wget -qO /dev/null -o /dev/null  http://localhost:8096/web/index.html || exit 1"]
        interval: 1h
        timeout: 10s
        retries: 5
        start_period: 30s
        start_interval: 0s
    ports:
      - 8096:8096
    restart: unless-stopped

  goemby_exporter:
    image: bagul/goemby_exporter:latest
    container_name: emby_exporter
    depends_on:
      emby:
        condition: service_healthy
    stdin_open: true
    ports:
      - 9210:9210
    tty: true
    environment:
      - CONFIG_FILE=/config/file.yml
    volumes:
      - ./emby_exporter_config/file.yml:/config/file.yml
```

The other solution would be to fix exit code logic. Since this project is no longer maintained and i will not submit a PR for modifying the current logic, would you be open to documenting a deployment example like this? I think it would helpful example to others.
